### ISSUE TITLE
安装完成后，执行报错

### ISSUE THREAD

**Issue by tcking** [alibaba-flutter/flutter-boot#21]
```
localhost:test2 didi$ flutter-boot init
/usr/local/lib/node_modules/flutter-boot/src/commands/init.js:24
    .action(async function () {
            ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/flutter-boot/index.js:12:1)
```

**Comment by voicewitness** [comment]
flutter-boot的版本号是多少

**Comment by voicewitness** [comment]
回复后开启
