### ISSUE TITLE
flutter-boot init error in link exist iOS project

### ISSUE THREAD

**Issue by xuzhenhao** [alibaba-flutter/flutter-boot#30]
? 是否存在iOS工程？ Yes
? iOS工程本地地址，回车跳过 /Users/Code/tempExercise/flutter/flutter_nsill [link] checking platform...
sill [link] linking...
(node:1664) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'link' of undefined
    at BaseLinker.link (/usr/local/lib/node_modules/flutter-boot/src/generator/linker.js:31:12)
    at init (/usr/local/lib/node_modules/flutter-boot/src/commands/init.js:80:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by xuzhenhao** [comment]
Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15 19A583, locale zh-Hans-CN)

**Comment by yinma848** [comment]
> Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15 19A583, locale zh-Hans-CN)

目前flutter-boot只适配到flutter1.9版本，对于1.12的支持还在开发中

**Comment by songjhh** [comment]
> > Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15 19A583, locale zh-Hans-CN)
> 
> 目前flutter-boot只适配到flutter1.9版本，对于1.12的支持还在开发中

1.12的支持什么时候发布啊？
