### ISSUE TITLE
flutter-boot init error

### ISSUE THREAD

**Issue by sunwillshine** [alibaba-flutter/flutter-boot#38]
flutter-boot init
info [init] init flutter module.
? 请输入flutter工程名称： my_flutter_module
? 请输入flutter仓库地址，回车跳过 
info [create] clean flutter module git
info [create] done: no git info
info [create] creating flutter module
Creating project my_flutter_module...
  my_flutter_module/test/widget_test.dart (created)
  my_flutter_module/my_flutter_module.iml (created)
  my_flutter_module/.gitignore (created)
  my_flutter_module/.metadata (created)
  my_flutter_module/pubspec.yaml (created)
  my_flutter_module/README.md (created)
  my_flutter_module/lib/main.dart (created)
  my_flutter_module/my_flutter_module_android.iml (created)
  my_flutter_module/.idea/libraries/Dart_SDK.xml (created)
  my_flutter_module/.idea/modules.xml (created)
  my_flutter_module/.idea/workspace.xml (created)
Running "flutter pub get" in my_flutter_module...                1,451ms
Wrote 11 files.

All done!
Your module code is in my_flutter_module/lib/main.dart.
sill [create] flutter module recorded
info [create] flutter module created
[!] The "make-host-app-editable" command is deprecated and will be removed in a future version of Flutter.
See https://flutter.dev/docs/development/tools/sdk/releases for previous releases of Flutter.

node:fs:784
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, rename '/Users/xxx/Desktop/Code/my_flutter_module/android' -> '/Users/xxx/Desktop/Code/my_flutter_module/android_shell'
    at Object.renameSync (node:fs:784:3)
    at generateShellProject (/usr/local/lib/node_modules/flutter-boot/src/generator/shellProject.js:29:6)
    at creator.createFlutterModule (/usr/local/lib/node_modules/flutter-boot/src/generator/creator.js:42:5)
    at creator.createModule (/usr/local/lib/node_modules/flutter-boot/src/generator/creator.js:20:35)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async init (/usr/local/lib/node_modules/flutter-boot/src/commands/init.js:59:3)
    at async Command.<anonymous> (/usr/local/lib/node_modules/flutter-boot/src/commands/init.js:27:7) {
  errno: -2,
  syscall: 'rename',
  code: 'ENOENT',
  path: '/Users/xxx/Desktop/Code/my_flutter_module/android',
  dest: '/Users/xxx/Desktop/Code/my_flutter_module/android_shell'
}

flutter --version
Flutter 1.24.0-10.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 022b333a08 (3 weeks ago) • 2020-11-18 11:35:09 -0800
Engine • revision 07c1eed46b
Tools • Dart 2.12.0 (build 2.12.0-29.10.beta)

flutter-boot --version
0.0.7

macOS Catalina 版本 10.15.7

这个工具还能用吗？执行报错了，求助。

**Comment by CNMathon** [comment]
同问，等一个回复

**Comment by penglimin** [comment]
同问， 这个my_flutter_module/android  下已经是./android 了。 肯定找不到吧？ 求解决。

**Comment by RenHaiRenWjc** [comment]
同问
