### ISSUE TITLE
Flutter 混合工程中 init 时报「SyntaxError: Unexpected token」

### ISSUE THREAD

**Issue by thirtyyuan** [alibaba-flutter/flutter-boot#8]
在 Flutter 工程目录下执行 `flutter-boot init` 命令，报错如下：
``` bash
/usr/local/lib/node_modules/flutter-boot/node_modules/del/index.js:89
module.exports.sync = (patterns, {force, dryRun, cwd = process.cwd(), ...options} = {}) => {
                                                                      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/flutter-boot/src/generator/creator.js:10:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

Flutter 版本信息如下:
```
Flutter 1.5.0 • channel unknown • unknown source
Framework • revision a18226d066 (6 months ago) • 2019-04-16 00:16:17 -0400
Engine • revision 9970fb5500
Tools • Dart 2.2.1 (build 2.2.1-dev.4.2 None)
```
请问要如何正确使用 flutter-boot 呢？

**Comment by voicewitness** [comment]
建议升级v8.9及以上的node版本
https://github.com/sindresorhus/del/issues/104#issuecomment-516559497
